# Generated by Django 6.0.5 on 2026-06-05 12:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_vendor_bank_details_vendor_mobile_number_and_more'),
        ('deliveries', '0001_initial'),
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_reference_code', models.CharField(max_length=120)),
                ('payment_stage', models.CharField(choices=[('advance', 'Advance'), ('against_dispatch', 'Against Dispatch'), ('against_delivery', 'Against Delivery'), ('after_installation', 'After Installation'), ('retention', 'Retention'), ('final_payment', 'Final Payment')], max_length=30)),
                ('payment_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('tds_deduction', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('net_payable', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('payment_due_date', models.DateField(blank=True, null=True)),
                ('payment_paid_date', models.DateField(blank=True, null=True)),
                ('payment_mode', models.CharField(blank=True, choices=[('neft', 'NEFT'), ('rtgs', 'RTGS'), ('upi', 'UPI'), ('cheque', 'Cheque'), ('cash', 'Cash')], max_length=20)),
                ('bank_transaction_id', models.CharField(blank=True, max_length=120)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('hold', 'Hold'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_payment_proof', models.FileField(blank=True, null=True, upload_to='po_documents/payment_proofs/')),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='purchase_orders.purchaseorder')),
                ('related_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='deliveries.delivery')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='deliveries.deliveryinvoicechallan')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_payments', to='core.vendor')),
            ],
            options={
                'ordering': ['payment_due_date', 'id'],
                'unique_together': {('po', 'payment_reference_code')},
            },
        ),
    ]
