# Generated by Django 6.0.5 on 2026-06-06 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_vendor_bank_details_vendor_mobile_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('assigned', 'Assigned to Staff'), ('reassigned', 'Reassigned'), ('task_created', 'Task Created'), ('task_updated', 'Task Updated'), ('document_uploaded', 'Document Uploaded'), ('po_created', 'PO Created'), ('delivery_updated', 'Delivery Updated'), ('payment_followup', 'Payment Follow-up'), ('note_added', 'Note Added')], max_length=30)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_activity_entries', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='core.vendor')),
            ],
            options={
                'db_table': 'vendor_activity_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
