# Generated by Django 6.0.5 on 2026-06-06 07:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('documentation', 'Documentation'), ('video', 'Video Tutorial'), ('faq', 'FAQ')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'help_resources',
                'ordering': ['resource_type', 'display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('attempted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'login_attempts',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.CreateModel(
            name='AppearanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('erp_logo', models.FileField(blank=True, null=True, upload_to='appearance/logos/')),
                ('sidebar_logo', models.FileField(blank=True, null=True, upload_to='appearance/sidebar/')),
                ('login_page_banner', models.FileField(blank=True, null=True, upload_to='appearance/banners/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='appearance/favicon/')),
                ('brand_primary_color', models.CharField(blank=True, default='#0d5cab', max_length=20)),
                ('brand_secondary_color', models.CharField(blank=True, default='#1b7f7a', max_length=20)),
                ('custom_css', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appearance_settings',
            },
        ),
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('manual', 'Manual'), ('scheduled', 'Scheduled')], default='manual', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='system_backups/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('restored_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'backup_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(default='Omega Group', max_length=255)),
                ('company_logo', models.FileField(blank=True, null=True, upload_to='company_settings/logos/')),
                ('company_address', models.TextField(blank=True)),
                ('gst_number', models.CharField(blank=True, max_length=50)),
                ('pan_number', models.CharField(blank=True, max_length=50)),
                ('cin_number', models.CharField(blank=True, max_length=50)),
                ('company_email', models.EmailField(blank=True, max_length=254)),
                ('company_phone', models.CharField(blank=True, max_length=50)),
                ('website_url', models.URLField(blank=True)),
                ('bank_details', models.TextField(blank=True)),
                ('authorized_signatory', models.CharField(blank=True, max_length=255)),
                ('digital_signature', models.FileField(blank=True, null=True, upload_to='company_settings/signatures/')),
                ('company_seal', models.FileField(blank=True, null=True, upload_to='company_settings/seals/')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_settings',
            },
        ),
        migrations.CreateModel(
            name='DashboardSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('widget_configuration_json', models.TextField(blank=True, default='{}')),
                ('hidden_modules_json', models.TextField(blank=True, default='[]')),
                ('quick_links_json', models.TextField(blank=True, default='[]')),
                ('custom_dashboard_json', models.TextField(blank=True, default='{}')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dashboard_settings',
            },
        ),
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, max_length=255)),
                ('smtp_password', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('sender_name', models.CharField(blank=True, max_length=255)),
                ('email_template_header', models.TextField(blank=True)),
                ('email_template_footer', models.TextField(blank=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_configurations',
            },
        ),
        migrations.CreateModel(
            name='ERPConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financial_year', models.CharField(blank=True, default='2026-2027', max_length=30)),
                ('default_currency', models.CharField(blank=True, default='INR', max_length=20)),
                ('tax_settings_json', models.TextField(blank=True, default='{}')),
                ('gst_settings_json', models.TextField(blank=True, default='{}')),
                ('invoice_number_format', models.CharField(blank=True, default='OMEGA/INV/{YEAR}/{AUTO_ID}', max_length=120)),
                ('po_number_format', models.CharField(blank=True, default='OMEGA/PO/{YEAR}/{AUTO_ID}', max_length=120)),
                ('vendor_code_format', models.CharField(blank=True, default='VEN-{AUTO_ID}', max_length=120)),
                ('employee_code_format', models.CharField(blank=True, default='EMP-{AUTO_ID}', max_length=120)),
                ('project_code_format', models.CharField(blank=True, default='PRJ-{YEAR}-{AUTO_ID}', max_length=120)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'erp_configurations',
            },
        ),
        migrations.CreateModel(
            name='MasterDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_type', models.CharField(choices=[('vendor_category', 'Vendor Categories'), ('material_category', 'Material Categories'), ('project_type', 'Project Types'), ('department', 'Departments'), ('designation', 'Designations'), ('location', 'Locations'), ('tax_category', 'Tax Categories'), ('payment_mode', 'Payment Modes')], max_length=40)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(blank=True, max_length=80)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata_json', models.TextField(blank=True, default='{}')),
            ],
            options={
                'db_table': 'master_data_entries',
                'ordering': ['master_type', 'display_order', 'name'],
                'unique_together': {('master_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SecuritySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minimum_password_length', models.PositiveIntegerField(default=8)),
                ('require_uppercase', models.BooleanField(default=True)),
                ('require_numbers', models.BooleanField(default=True)),
                ('require_special_characters', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=60)),
                ('ip_restrictions', models.TextField(blank=True)),
                ('device_restrictions', models.TextField(blank=True)),
                ('login_attempt_limit', models.PositiveIntegerField(default=5)),
                ('audit_logging_enabled', models.BooleanField(default=True)),
                ('force_password_change_days', models.PositiveIntegerField(default=90)),
                ('two_factor_required', models.BooleanField(default=False)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_settings',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_role', models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR'), ('accounts', 'Accounts'), ('purchase_manager', 'Purchase Manager'), ('vendor_manager', 'Vendor Manager'), ('purchase_staff', 'Purchase Staff'), ('accounts_staff', 'Accounts Staff'), ('site_staff', 'Site Staff'), ('site_engineer', 'Site Engineer'), ('project_manager', 'Project Manager'), ('viewer', 'Viewer')], max_length=40)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-updated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('password_change', 'Password Change'), ('user_create', 'User Creation'), ('user_delete', 'User Deletion'), ('vendor_assignment', 'Vendor Assignment'), ('po_change', 'PO Change'), ('payment_update', 'Payment Update'), ('settings_change', 'Settings Change'), ('generic', 'Generic')], default='generic', max_length=40)),
                ('module', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('device_information', models.TextField(blank=True)),
                ('metadata_json', models.TextField(blank=True, default='{}')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'system_audit_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('whatsapp_notifications', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('browser_push_notifications', models.BooleanField(default=False)),
                ('event_preferences_json', models.TextField(blank=True, default='{}')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='UserSessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('logged_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_session_records',
                'ordering': ['-last_activity_at', '-logged_in_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_provider', models.CharField(blank=True, max_length=120)),
                ('access_token', models.TextField(blank=True)),
                ('phone_number_id', models.CharField(blank=True, max_length=120)),
                ('business_account_id', models.CharField(blank=True, max_length=120)),
                ('webhook_url', models.URLField(blank=True)),
                ('template_management_json', models.TextField(blank=True, default='{}')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'whatsapp_configurations',
            },
        ),
    ]
