# Generated by Django 6.0.5 on 2026-06-04 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'business_units',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaterialMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_code', models.CharField(blank=True, max_length=100)),
                ('work_package', models.CharField(blank=True, max_length=150)),
                ('material_name', models.CharField(blank=True, max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('qty_specification', models.CharField(blank=True, max_length=100)),
                ('no_of_site', models.CharField(blank=True, max_length=100)),
                ('mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('lt_panel', models.CharField(blank=True, max_length=255)),
                ('lt_panels', models.CharField(blank=True, max_length=255)),
                ('pf_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material_master',
            },
        ),
        migrations.CreateModel(
            name='ProjectMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_code', models.CharField(blank=True, max_length=50, unique=True)),
                ('project_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('procurement_source', models.CharField(blank=True, max_length=100)),
                ('business_unit', models.CharField(blank=True, max_length=255)),
                ('project_location', models.CharField(blank=True, max_length=255)),
                ('total_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_master',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('experience_details', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('address2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('pin_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('vendor_type', models.CharField(blank=True, max_length=100)),
                ('vendor_category', models.CharField(blank=True, max_length=100)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('email_id', models.EmailField(blank=True, max_length=254)),
                ('attendee_name', models.CharField(blank=True, max_length=200)),
                ('bde_name', models.CharField(blank=True, max_length=200)),
                ('meeting_with', models.CharField(blank=True, max_length=200)),
                ('qualification_status', models.CharField(blank=True, max_length=50)),
                ('msme_reg', models.CharField(blank=True, max_length=100)),
                ('pan_no', models.CharField(blank=True, max_length=30)),
                ('pf_reg', models.CharField(blank=True, max_length=100)),
                ('gst_no', models.CharField(blank=True, max_length=30)),
                ('gst_type', models.CharField(blank=True, max_length=100)),
                ('gst_status', models.CharField(blank=True, max_length=100)),
                ('last_gstr1', models.CharField(blank=True, max_length=20)),
                ('gst_pending_status', models.CharField(blank=True, max_length=100)),
                ('aadhaar_no', models.CharField(blank=True, max_length=20)),
                ('labour_welfare_fund', models.CharField(blank=True, max_length=100)),
                ('professional_tax', models.CharField(blank=True, max_length=100)),
                ('turnover_year_1', models.CharField(blank=True, max_length=100)),
                ('turnover_year_2', models.CharField(blank=True, max_length=100)),
                ('turnover_year_3', models.CharField(blank=True, max_length=100)),
                ('bank_account_name', models.CharField(blank=True, max_length=150)),
                ('bank_name_address', models.TextField(blank=True)),
                ('account_type', models.CharField(blank=True, max_length=50)),
                ('account_number', models.CharField(blank=True, max_length=30)),
                ('bank_proof_type', models.CharField(blank=True, max_length=50)),
                ('passbook_file', models.FileField(blank=True, null=True, upload_to='vendor_docs/')),
                ('client_list_data', models.TextField(blank=True)),
                ('vendor_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_registration',
            },
        ),
        migrations.CreateModel(
            name='WorkPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'work_packages',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectPlanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_unit', models.CharField(blank=True, max_length=255)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('procurement_source', models.CharField(blank=True, max_length=100)),
                ('project_location', models.CharField(blank=True, max_length=255)),
                ('mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('planner_note', models.TextField(blank=True)),
                ('work_plan_json', models.TextField(blank=True)),
                ('material_plan_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead_vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
            ],
            options={
                'db_table': 'project_planner',
            },
        ),
        migrations.CreateModel(
            name='MaterialQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_reference', models.CharField(blank=True, max_length=120)),
                ('project_name', models.CharField(blank=True, max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('work_type', models.CharField(blank=True, max_length=150)),
                ('mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('file_type', models.CharField(blank=True, max_length=20)),
                ('note', models.TextField(blank=True)),
                ('line_items_json', models.TextField(blank=True)),
                ('total_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
            ],
            options={
                'db_table': 'material_quotation',
            },
        ),
        migrations.CreateModel(
            name='ProjectWorkAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('scope_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='core.projectmaster')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vendor')),
                ('work_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workpackage')),
            ],
            options={
                'db_table': 'project_work_allocation',
            },
        ),
    ]
