# Generated by Django 6.0.5 on 2026-06-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='bank_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='vendor',
            name='status',
            field=models.CharField(blank=True, default='active', max_length=30),
        ),
        migrations.AddField(
            model_name='vendor',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
