# Generated by Django 6.0.5 on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_vendor_bank_details_vendor_mobile_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectworkallocation',
            name='actual_completion_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectworkallocation',
            name='completed_mw',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='projectworkallocation',
            name='timeline_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectworkallocation',
            name='timeline_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
