# Generated by Django 6.0.5 on 2026-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectworkallocation_actual_completion_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmaster',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='materialmaster',
            name='hsn_code',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
