# Generated by Django 6.0.5 on 2026-06-06 12:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_projectworkallocation_actual_completion_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255)),
                ('site_code', models.CharField(blank=True, max_length=100)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('district', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('capacity_mw', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('work_type', models.CharField(blank=True, max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('assigned_scope', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ai_health_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_assignments', to='core.projectworkallocation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_portal_assignments', to='core.projectmaster')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_project_assignments', to='core.vendor')),
            ],
            options={
                'db_table': 'vendor_portal_project_assignments',
                'ordering': ['project__project_name', 'site_name', 'work_type'],
            },
        ),
        migrations.CreateModel(
            name='VendorIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_type', models.CharField(choices=[('material_shortage', 'Material Shortage'), ('labour_shortage', 'Labour Shortage'), ('technical_issue', 'Technical Issue'), ('weather_delay', 'Weather Delay'), ('safety_issue', 'Safety Issue'), ('client_issue', 'Client Issue'), ('equipment_breakdown', 'Equipment Breakdown')], max_length=40)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='vendor_portal/issues/')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('raised_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='vendor_portal.vendorprojectassignment')),
            ],
            options={
                'db_table': 'vendor_portal_issues',
                'ordering': ['-raised_date'],
            },
        ),
        migrations.CreateModel(
            name='VendorDailyUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_date', models.DateField(default=django.utils.timezone.localdate)),
                ('work_category', models.CharField(max_length=150)),
                ('work_description', models.TextField()),
                ('todays_achievement', models.TextField(blank=True)),
                ('quantity_completed', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('progress_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('manpower_used', models.PositiveIntegerField(default=0)),
                ('equipment_used', models.TextField(blank=True)),
                ('material_consumed', models.TextField(blank=True)),
                ('issues_faced', models.TextField(blank=True)),
                ('delay_reasons', models.TextField(blank=True)),
                ('tomorrow_plan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('verified', 'Verified')], default='draft', max_length=30)),
                ('ai_completion_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ai_delay_risk_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='vendor_portal.vendorprojectassignment')),
            ],
            options={
                'db_table': 'vendor_portal_daily_updates',
                'ordering': ['-update_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('revision_requested', 'Revision Requested'), ('verified', 'Verified')], max_length=30)),
                ('comments', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('daily_update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='vendor_portal.vendordailyupdate')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_portal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'vendor_portal_reviews',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('vendor_admin', 'Vendor Admin'), ('vendor_supervisor', 'Vendor Supervisor'), ('vendor_engineer', 'Vendor Engineer'), ('vendor_operator', 'Vendor Operator')], default='vendor_operator', max_length=40)),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('otp_code', models.CharField(blank=True, max_length=12)),
                ('otp_generated_at', models.DateTimeField(blank=True, null=True)),
                ('otp_verified_at', models.DateTimeField(blank=True, null=True)),
                ('last_login_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_users', to='core.vendor')),
            ],
            options={
                'db_table': 'vendor_portal_users',
                'ordering': ['vendor__company_name', 'user__username'],
            },
        ),
        migrations.AddField(
            model_name='vendorprojectassignment',
            name='vendor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='vendor_portal.vendoruser'),
        ),
        migrations.CreateModel(
            name='VendorPortalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=80)),
                ('ip_address', models.CharField(blank=True, max_length=100)),
                ('user_agent', models.TextField(blank=True)),
                ('logged_in_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_activity_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('logged_out_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vendor_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_sessions', to='vendor_portal.vendoruser')),
            ],
            options={
                'db_table': 'vendor_portal_sessions',
                'ordering': ['-last_activity_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('channel', models.CharField(choices=[('erp', 'ERP Notification'), ('email', 'Email'), ('whatsapp', 'WhatsApp')], default='erp', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('read', 'Read'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('daily_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vendor_portal.vendordailyupdate')),
                ('issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vendor_portal.vendorissue')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vendor_portal.vendorprojectassignment')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vendor_portal.vendoruser')),
            ],
            options={
                'db_table': 'vendor_portal_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20)),
                ('file', models.FileField(upload_to='vendor_portal/media/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('gps_latitude', models.CharField(blank=True, max_length=50)),
                ('gps_longitude', models.CharField(blank=True, max_length=50)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('watermark_text', models.CharField(blank=True, max_length=255)),
                ('ai_progress_detection_json', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('daily_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_entries', to='vendor_portal.vendordailyupdate')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_entries', to='vendor_portal.vendorprojectassignment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_entries', to='vendor_portal.vendoruser')),
            ],
            options={
                'db_table': 'vendor_portal_media',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='vendorissue',
            name='vendor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='vendor_portal.vendoruser'),
        ),
        migrations.CreateModel(
            name='VendorDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('site_report', 'Site Report'), ('test_certificate', 'Test Certificate'), ('inspection_report', 'Inspection Report'), ('drawing', 'CAD Drawing'), ('general', 'General Document')], default='general', max_length=40)),
                ('file', models.FileField(upload_to='vendor_portal/documents/')),
                ('remarks', models.TextField(blank=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('daily_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendor_portal.vendordailyupdate')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendor_portal.vendorprojectassignment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='vendor_portal.vendoruser')),
            ],
            options={
                'db_table': 'vendor_portal_documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.AddField(
            model_name='vendordailyupdate',
            name='vendor_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_updates', to='vendor_portal.vendoruser'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorprojectassignment',
            unique_together={('vendor_user', 'project', 'allocation')},
        ),
    ]
