# Generated by Django 6.0.5 on 2026-06-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR'), ('accounts', 'Accounts'), ('purchase_manager', 'Purchase Manager'), ('vendor_manager', 'Vendor Manager'), ('purchase_staff', 'Purchase Staff'), ('accounts_staff', 'Accounts Staff'), ('site_staff', 'Site Staff'), ('site_engineer', 'Site Engineer'), ('project_manager', 'Project Manager'), ('viewer', 'Viewer')], max_length=40)),
                ('module_key', models.CharField(choices=[('vendors', 'Vendors'), ('purchase_orders', 'Purchase Orders'), ('deliveries', 'Deliveries'), ('inventory', 'Inventory'), ('payments', 'Payments'), ('projects', 'Projects'), ('reports', 'Reports'), ('accounts', 'Accounts'), ('settings', 'Settings & Administration')], max_length=40)),
                ('can_view', models.BooleanField(default=False)),
                ('can_create', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_approve', models.BooleanField(default=False)),
                ('can_export', models.BooleanField(default=False)),
                ('can_assign', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'role_permissions',
                'ordering': ['role', 'module_key'],
                'unique_together': {('role', 'module_key')},
            },
        ),
    ]
