# Generated by Django 6.0.5 on 2026-06-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='currency_format',
            field=models.CharField(blank=True, default='INR', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='dashboard_layout',
            field=models.CharField(blank=True, default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_format',
            field=models.CharField(blank=True, default='DD MMM YYYY', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='default_landing_page',
            field=models.CharField(blank=True, default='dashboard', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='force_password_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='notification_preferences_json',
            field=models.TextField(blank=True, default='{}'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='staff_profiles/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='security_answer_hint',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='security_question',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='theme_preference',
            field=models.CharField(blank=True, default='system', max_length=20),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='time_zone',
            field=models.CharField(blank=True, default='Asia/Calcutta', max_length=100),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin'), ('hr', 'HR'), ('accounts', 'Accounts'), ('purchase_manager', 'Purchase Manager'), ('vendor_manager', 'Vendor Manager'), ('purchase_staff', 'Purchase Staff'), ('accounts_staff', 'Accounts Staff'), ('site_staff', 'Site Staff'), ('site_engineer', 'Site Engineer'), ('project_manager', 'Project Manager'), ('viewer', 'Viewer')], max_length=40),
        ),
    ]
