# Generated by Django 6.0.5 on 2026-06-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('report_type', models.CharField(choices=[('po_summary', 'PO Summary Report'), ('vendor_po', 'Vendor-wise PO Report'), ('material_delivery', 'Material-wise Delivery Report'), ('vehicle_tracking', 'Vehicle Tracking Report'), ('pending_delivery', 'Pending Delivery Report'), ('part_payment', 'Part-wise Payment Report'), ('outstanding_payment', 'Outstanding Vendor Payment Report'), ('invoice_payment', 'Invoice vs Payment Report')], max_length=40)),
                ('filters_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
