# Generated by Django 6.0.5 on 2026-06-05 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
        ('payments', '0001_initial'),
        ('purchase_orders', '0001_initial'),
        ('transport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('po_copy', 'PO Copy'), ('vendor_quotation', 'Vendor Quotation'), ('invoice', 'Invoice'), ('challan', 'Challan'), ('eway_bill', 'E-way Bill'), ('lr_copy', 'LR Copy'), ('payment_proof', 'Payment Proof'), ('quality_check', 'Quality Check Report'), ('site_receiving', 'Site Receiving Report'), ('other', 'Other')], default='other', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='po_documents/library/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='deliveries.delivery')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.vendorpayment')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='purchase_orders.purchaseorder')),
                ('reference_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='purchase_orders.purchaseorderreferencecode')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_business_documents', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='transport.vehiclemovement')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('delivery_delayed', 'Delivery Delayed'), ('vehicle_reached', 'Vehicle Reached Site'), ('payment_due', 'Pending Payment Due'), ('invoice_pending', 'Invoice Pending Verification'), ('po_partial', 'PO Partially Delivered'), ('po_full', 'PO Fully Delivered'), ('approval_required', 'Payment Approval Required')], max_length=40)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp')], default='email', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=120)),
                ('recipient_contact', models.CharField(max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='deliveries.delivery')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='payments.vendorpayment')),
                ('po', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
