# Generated by Django 6.0.5 on 2026-06-06 06:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('core', '0002_vendor_bank_details_vendor_mobile_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_assignment_changes', to=settings.AUTH_USER_MODEL)),
                ('new_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_vendor_histories', to='accounts.staffprofile')),
                ('previous_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_vendor_histories', to='accounts.staffprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_history', to='core.vendor')),
            ],
            options={
                'db_table': 'vendor_assignment_history',
                'ordering': ['-changed_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='VendorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('primary', 'Primary Staff'), ('supporting', 'Supporting Staff')], default='primary', max_length=20)),
                ('assignment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=django.utils.timezone.localdate)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignment_status', models.CharField(choices=[('active', 'Active'), ('reassigned', 'Reassigned'), ('removed', 'Removed'), ('on_hold', 'On Hold')], default='active', max_length=20)),
                ('assignment_reason', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vendor_records', to=settings.AUTH_USER_MODEL)),
                ('assigned_staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendor_assignments', to='accounts.staffprofile')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.vendor')),
            ],
            options={
                'db_table': 'vendor_assignments',
                'ordering': ['vendor__company_name', 'assignment_role', '-start_date'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('assignment_role', 'primary'), ('assignment_status', 'active')), fields=('vendor',), name='unique_active_primary_vendor_assignment')],
            },
        ),
    ]
