# Generated by Django 6.0.5 on 2026-06-05 12:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(blank=True, max_length=80)),
                ('driver_name', models.CharField(blank=True, max_length=120)),
                ('driver_mobile_number', models.CharField(blank=True, max_length=20)),
                ('transporter_name', models.CharField(blank=True, max_length=150)),
                ('lr_number', models.CharField(blank=True, max_length=120)),
                ('e_way_bill_number', models.CharField(blank=True, max_length=120)),
                ('dispatch_date', models.DateField(blank=True, null=True)),
                ('expected_arrival_date', models.DateField(blank=True, null=True)),
                ('actual_arrival_date', models.DateField(blank=True, null=True)),
                ('gps_tracking_link', models.URLField(blank=True)),
                ('loading_location', models.CharField(blank=True, max_length=255)),
                ('unloading_location', models.CharField(blank=True, max_length=255)),
                ('freight_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('transport_payment_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('hold', 'Hold')], default='pending', max_length=20)),
                ('vehicle_status', models.CharField(choices=[('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('reached_site', 'Reached Site'), ('unloaded', 'Unloaded'), ('delayed', 'Delayed')], default='dispatched', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='deliveries.delivery')),
            ],
            options={
                'ordering': ['-dispatch_date', '-id'],
            },
        ),
    ]
