# Generated by Django 6.0.5 on 2026-06-05 12:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_vendor_bank_details_vendor_mobile_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_number', models.CharField(max_length=80, unique=True)),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('business_division', models.CharField(choices=[('solar', 'Solar'), ('biogas', 'Biogas'), ('infrastructure', 'Infrastructure'), ('pharma', 'Pharma'), ('other', 'Other')], default='solar', max_length=30)),
                ('project_site_name', models.CharField(max_length=255)),
                ('project_location', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('total_po_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('payment_terms', models.TextField(blank=True)),
                ('delivery_terms', models.TextField(blank=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('quotation_document', models.FileField(blank=True, null=True, upload_to='po_documents/quotations/')),
                ('po_copy', models.FileField(blank=True, null=True, upload_to='po_documents/po_copies/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('partially_delivered', 'Partially Delivered'), ('fully_delivered', 'Fully Delivered'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('delivery_status_summary', models.CharField(choices=[('pending', 'Pending'), ('partially_delivered', 'Partially Delivered'), ('fully_delivered', 'Fully Delivered')], default='pending', max_length=30)),
                ('payment_status_summary', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('fully_paid', 'Fully Paid')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='core.vendor')),
            ],
            options={
                'ordering': ['-po_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('metadata_json', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_activity_logs', to=settings.AUTH_USER_MODEL)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_category', models.CharField(max_length=120)),
                ('material_name', models.CharField(max_length=255)),
                ('specification', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, max_length=120)),
                ('model', models.CharField(blank=True, max_length=120)),
                ('unit', models.CharField(max_length=50)),
                ('ordered_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('unit_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('gst_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('item_status', models.CharField(choices=[('pending', 'Pending'), ('partially_delivered', 'Partially Delivered'), ('fully_delivered', 'Fully Delivered'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderReferenceCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(max_length=120)),
                ('reference_type', models.CharField(choices=[('vendor_reference', 'Vendor Reference'), ('transport_reference', 'Transport Reference'), ('invoice_reference', 'Invoice Reference'), ('project_reference', 'Project Reference'), ('payment_reference', 'Payment Reference'), ('dispatch_reference', 'Dispatch Reference')], max_length=40)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('uploaded_document', models.FileField(blank=True, null=True, upload_to='po_documents/reference_codes/')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_codes', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['-date', '-id'],
                'unique_together': {('po', 'reference_code')},
            },
        ),
    ]
