# Generated by Django 6.0.5 on 2026-07-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_projectworkallocation_actual_completion_date_and_more'),
        ('purchase_orders', '0003_purchaseorder_vendor_tracking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='core.materialmaster'),
        ),
    ]
