# Generated by Django 6.0.5 on 2026-07-29 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_orders', '0005_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='client_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='client_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sender_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sender_mobile',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
