# Generated by Django 6.0.5 on 2026-06-05 12:14

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase_orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_reference_code', models.CharField(max_length=120)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('delivered_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_quantity_after_delivery', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('delivery_location', models.CharField(blank=True, max_length=255)),
                ('site_received_by', models.CharField(blank=True, max_length=120)),
                ('quality_checked_by', models.CharField(blank=True, max_length=120)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('partially_received', 'Partially Received'), ('received', 'Received'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('quality_check_report', models.FileField(blank=True, null=True, upload_to='po_documents/quality_reports/')),
                ('site_receiving_report', models.FileField(blank=True, null=True, upload_to='po_documents/site_receiving/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='purchase_orders.purchaseorder')),
                ('po_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='purchase_orders.purchaseorderitem')),
            ],
            options={
                'ordering': ['delivery_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryInvoiceChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challan_number', models.CharField(blank=True, max_length=120)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=120)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('uploaded_challan', models.FileField(blank=True, null=True, upload_to='po_documents/challans/')),
                ('uploaded_invoice', models.FileField(blank=True, null=True, upload_to='po_documents/invoices/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_challans', to='deliveries.delivery')),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_challans', to='purchase_orders.purchaseorder')),
            ],
            options={
                'ordering': ['-invoice_date', '-challan_date', '-id'],
            },
        ),
    ]
